# Generated by Django 4.2.9 on 2024-01-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_like_blog_post_remove_like_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='read_time_minutes',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('pending_approval', 'Pending Approval')], default='pending_approval', max_length=20),
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
